name: Deploy from Svelte to Github Pages

# By the way this is taken from
# https://www.captaincodeman.com/deploy-a-sveltekit-app-to-github-pages

on:
  # Trigger the workflow on every push to the main branch
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies (website)
        # Install dependencies for the Svelte site located in the `website` subfolder.
        run: pnpm --dir website install --frozen-lockfile

      - name: Generate newsletter articles
        # Run the local script that converts markdown files into the generated JSON
        # used by the app. This must run before building so the generated JSON is
        # included in the built site.
        run: node website/scripts/generate-articles.mjs

      - name: Build site
        # Build the SvelteKit site (produces `build/` inside the `website` folder).
        run: pnpm --dir website build

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: sveltekit
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the build output from the website subfolder.
          path: 'website/build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
